# Generated by Django 5.1.1 on 2024-11-02 01:14

from django.db import migrations, models
import json


def create_chapter_models(apps, schema_editor):

    print("Creating chapter models...")

    # Get the model from the historical version
    Chapters = apps.get_model('IFC', 'Chapter')
    # Create predefined instances

    file = open('setup/init_chapter_data.json', 'r')
    data = json.load(file)

    for i in range(len(data)):
        ch = data[i]
        Chapters.objects.create(
            name=ch["name"],
            letters=ch["letters"],
            rush_chair=ch["rush_chair"],
            president=ch["president"],
            info=ch["info"],
            chapter_size=ch["chapter_size"],
            image=ch["image"]
        )

    file.close()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('letters', models.CharField(max_length=10)),
                ('rush_chair', models.CharField(max_length=255)),
                ('president', models.CharField(max_length=255)),
                ('info', models.TextField(max_length=900)),
                ('chapter_size', models.PositiveIntegerField()),
                ('image', models.ImageField(default='chapters/default.jpg', upload_to='chapters/')),
            ],
        ),
        migrations.RunPython(create_chapter_models)
    ]
