# Generated by Django 5.1.1 on 2024-10-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("letters", models.CharField(max_length=10)),
                ("rush_chair", models.CharField(max_length=255)),
                ("president", models.CharField(max_length=255)),
                ("info", models.TextField(max_length=900)),
                ("chapter_size", models.PositiveIntegerField()),
            ],
        ),
    ]
