# Generated by Django 5.1.1 on 2024-10-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFC", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
