# Generated by Django 5.1.1 on 2024-10-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFC', '0002_chapter_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='image',
            field=models.ImageField(default='media/chapters/default.jpg', upload_to='chapters/'),
        ),
    ]
