# Generated by Django 5.1.1 on 2024-11-01 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IFC', '0003_chapter_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='slug',
        ),
    ]
