# Generated by Django 5.1.1 on 2024-10-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFC", "0003_chapter_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="council",
            field=models.CharField(default="none", max_length=100),
        ),
    ]
